Use the mock that finds a working implementation
Instead of using the library provided mock, use the import
logic in our tests module that tries to find the best one that is
usable in the current environment. It appears that this logic
is *still* needed due to bugs in the non-bundled mock that
causes errors/exceptions such as:

AttributeError: 'method-wrapper' object has no attribute '__module__'

It seems this is related to (or is this same) upstream bug:

- https://code.google.com/p/mock/issues/detail?id=234

Change-Id: Ifeb3017f43b7d34af155ceca35d040706d34b185