Fix duplicate table_name argument
Fix the following error caused by the regression introduced by
72df15e629883b78d7a922e3b2ea6f78b13b73e4 .

TypeError: CreateIndexOp.__init__() got multiple values for argument
'table_name'

Closes-Bug: #2111806
Change-Id: I3e941ffbb0193056e8e271bf96f6a841a2ba95c0